### ISSUE TITLE
Зачем GPS?

### ISSUE THREAD

**Issue by MinerChAI** [Bougakov/wallclock#1]
Зачем GPS? Можно брать время со звонка. Тогда вне зависимости от того, где звонок берет время, часы будут показывать правильное время.

**Comment by Bougakov** [comment]
В школе WiFi с RADIUS-авторизацией через портал госуслуг, ходить на NTP-сервер невозможно. Уже пробовали с RaspberryPi и WiFi, не выходит.

Контроллер звонка стоит на 1 этаже, а часы будут висеть на третьем.
